### PR TITLE
fix README.md

### PR DESCRIPTION
**Pull request by bicycle1885**

### CODE REVIEW

**Review by timbitz — APPROVED** [review]

**Comment by bicycle1885** [comment]
Hi, @timbitz. I tagged [v0.1](https://github.com/JuliaLang/METADATA.jl/pull/11609). We use [AttoBot](https://github.com/attobot/attobot) to release BioJulia packages, and so I recommend you to use it when you do.

**Comment by timbitz** [comment]
OK thanks @bicycle1885. So if Attobot is already installed in the repo and and I draft a new release it will automatically trigger the PR to METADATA.jl right?

**Comment by bicycle1885** [comment]
Right. AttoBot is the easiest way to release packages AFAIK.

**Comment by timbitz** [comment]
OK cool, sounds good.

**Pull request merged**
